@extends('layouts.department')

@section('content')
@php $data = old() ?: ($form->form_data ?? []); $location = ($project->location_description ?? ($project->barangay->barangay_name ?? 'Citywide')) . ', Cabuyao City, Laguna'; @endphp
<div class="space-y-6">
    <div><h1 class="text-2xl font-bold text-black">Form 3 — Project Exception Report</h1><p class="text-sm text-gray-500 mt-1">{{ $project->project_name }} ({{ $project->project_code }})</p><p class="text-xs text-gray-400 mt-1">@if ($form) Form created on {{ $form->created_at->format('M d, Y h:i A') }} &middot; Last updated {{ $form->updated_at->format('M d, Y h:i A') }} @else Not yet filled out @endif</p></div>
    @if ($errors->any())<div class="bg-red-50 border border-red-300 text-red-700 rounded-md p-3 text-sm"><ul class="list-disc list-inside">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('department.projects.forms.update', [$project->project_id, 'form_3']) }}" class="space-y-6">@csrf @method('PUT')
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;"><h2 class="text-lg font-bold text-black">Project Information</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div><label class="block text-sm font-medium text-black">Implementing Agency/NGOs/Concerned Citizens</label><input type="text" name="implementing_agency" value="{{ old('implementing_agency', $data['implementing_agency'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
            <div><label class="block text-sm font-medium text-black">Program/Project Title</label><input type="text" value="{{ $project->project_name }}" readonly class="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-100" style="border-color: #B2BEB5; color: black;"><p class="text-xs text-gray-500 mt-1">Auto-filled from project record.</p></div>
            <div><label class="block text-sm font-medium text-black">Implementing Agency Type</label>@php $agencyType = old('implementing_agency_type', $data['implementing_agency_type'] ?? ''); @endphp<select name="implementing_agency_type" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"><option value="">-- Select --</option><option value="LGU" @selected($agencyType === 'LGU')>LGU</option></select></div>
            <div><label class="block text-sm font-medium text-black">Sector</label>@php $sector = old('sector', $data['sector'] ?? ''); @endphp<select name="sector" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"><option value="">-- Select --</option>@foreach (['General Public Services', 'Social Services', 'Economic Services', 'Other Services'] as $option)<option value="{{ $option }}" @selected($sector === $option)>{{ $option }}</option>@endforeach</select></div>
            <div class="md:col-span-2"><label class="block text-sm font-medium text-black">Location</label><input type="text" value="{{ $location }}" readonly class="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-100" style="border-color: #B2BEB5; color: black;"><p class="text-xs text-gray-500 mt-1">Auto-filled from project record.</p></div>
        </div></div>
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;"><h2 class="text-lg font-bold text-black">Exception Details</h2><div><label class="block text-sm font-medium text-black">Findings</label><textarea name="findings" rows="3" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;">{{ old('findings', $data['findings'] ?? '') }}</textarea></div><div><label class="block text-sm font-medium text-black">Typology</label>@php $typology = old('typology', $data['typology'] ?? ''); @endphp<select name="typology" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"><option value="">-- Select --</option>@foreach (['Site Condition/Availability', 'Procurement', 'Government/Funding Institution Approvals', 'Budget and Funds Flow', 'Design, Scope, Technical Specifications', 'Performance of Contractors/Consultants', 'Capacity of Project Management Unit and Other Implementing Partners', 'Institutional Support', 'Inputs and Costs', 'Legal and Policy Issuances', 'Sustainability, Operations and Maintenance', 'Force Majeure', 'Others'] as $option)<option value="{{ $option }}" @selected($typology === $option)>{{ $option }}</option>@endforeach</select></div><div><label class="block text-sm font-medium text-black">Issue Status</label><input type="text" name="issue_status" value="{{ old('issue_status', $data['issue_status'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@foreach (['reasons' => 'Reasons', 'actions_taken' => 'Actions Taken', 'actions_to_be_taken' => 'Actions to be Taken'] as $field => $label)<div><label class="block text-sm font-medium text-black">{{ $label }}</label><textarea name="{{ $field }}" rows="3" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;">{{ old($field, $data[$field] ?? '') }}</textarea></div>@endforeach</div>
        @include('department.projects.forms.signatories', ['project' => $project, 'data' => $data])
        <div class="flex justify-end space-x-3"><a href="{{ route('department.projects.show', $project->project_id) }}" class="px-4 py-2 rounded" style="background-color: #e5e7eb;">Cancel</a><button type="submit" class="px-4 py-2 rounded" style="background-color: #162347; color: #f2f3f7;">Save Form</button></div>
    </form>
</div>
@endsection
