@extends('layouts.department')

@section('content')
@php $data = old() ?: ($form->form_data ?? []); @endphp
<div class="space-y-6">
    <div>
        <h1 class="text-2xl font-bold text-black">Form 2 — Physical and Financial Accomplishment Report</h1>
        <p class="text-sm text-gray-500 mt-1">{{ $project->project_name }} ({{ $project->project_code }})</p>
        <p class="text-xs text-gray-400 mt-1">@if ($form) Form created on {{ $form->created_at->format('M d, Y h:i A') }} &middot; Last updated {{ $form->updated_at->format('M d, Y h:i A') }} @else Not yet filled out @endif</p>
    </div>
    @if ($errors->any())<div class="bg-red-50 border border-red-300 text-red-700 rounded-md p-3 text-sm"><ul class="list-disc list-inside">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('department.projects.forms.update', [$project->project_id, 'form_2']) }}" class="space-y-6">@csrf @method('PUT')
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;">
            <h2 class="text-lg font-bold text-black">Project Information</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div><label class="block text-sm font-medium text-black">Implementing Agency</label><input type="text" name="implementing_agency" value="{{ old('implementing_agency', $data['implementing_agency'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
                <div><label class="block text-sm font-medium text-black">Program/Project Title</label><input type="text" value="{{ $project->project_name }}" readonly class="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-100" style="border-color: #B2BEB5; color: black;"><p class="text-xs text-gray-500 mt-1">Auto-filled from project record.</p></div>
                <div><label class="block text-sm font-medium text-black">Implementation Start Date</label><input type="date" name="start_date" value="{{ old('start_date', $data['start_date'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
                <div><label class="block text-sm font-medium text-black">Implementation End Date</label><input type="date" name="end_date" value="{{ old('end_date', $data['end_date'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
                <div><label class="block text-sm font-medium text-black">Fund Source</label>@php $fundSource = old('fund_source', $data['fund_source'] ?? ''); @endphp<select name="fund_source" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"><option value="">-- Select --</option>@foreach (['ODA Loan', 'ODA Grant', 'ODA Loan and Grant', 'LFP', 'PPP', 'NTA', 'Local Development Fund'] as $option)<option value="{{ $option }}" @selected($fundSource === $option)>{{ $option }}</option>@endforeach</select></div>
                <div><label class="block text-sm font-medium text-black">Funding Agency</label><input type="text" name="funding_agency" value="{{ old('funding_agency', $data['funding_agency'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
                <div><label class="block text-sm font-medium text-black">Total Project Cost (PHP)</label><input type="text" name="total_project_cost" value="{{ old('total_project_cost', $data['total_project_cost'] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>
            </div>
        </div>
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;"><h2 class="text-lg font-bold text-black">Financial Status (PHP)</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-4">@foreach (['appropriations' => 'Appropriations', 'allotment' => 'Allotment', 'obligations' => 'Obligations', 'disbursements' => 'Disbursements'] as $field => $label)<div><label class="block text-sm font-medium text-black">{{ $label }}</label><input type="text" name="{{ $field }}" value="{{ old($field, $data[$field] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@endforeach</div></div>
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;"><h2 class="text-lg font-bold text-black">Physical Accomplishment</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-4">@foreach (['target_owpa_to_date' => 'Target OWPA to Date', 'actual_owpa_to_date' => 'Actual OWPA to Date', 'slippage' => 'Slippage'] as $field => $label)<div><label class="block text-sm font-medium text-black">{{ $label }}</label><input type="text" name="{{ $field }}" value="{{ old($field, $data[$field] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@endforeach</div><div class="grid grid-cols-1 md:grid-cols-2 gap-4">@for ($i = 1; $i <= 5; $i++)<div><label class="block text-sm font-medium text-black">Output Indicator {{ $i }}</label><input type="text" name="output_indicator_{{ $i }}" value="{{ old("output_indicator_{$i}", $data["output_indicator_{$i}"] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@endfor</div><div class="grid grid-cols-1 md:grid-cols-3 gap-4">@foreach (['end_of_project_target' => 'End of Project Target', 'target_to_date' => 'Target to Date', 'actual_to_date' => 'Actual to Date'] as $field => $label)<div><label class="block text-sm font-medium text-black">{{ $label }}</label><input type="date" name="{{ $field }}" value="{{ old($field, $data[$field] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@endforeach</div></div>
        <div class="bg-white rounded-lg p-6 space-y-4" style="border: 1px solid #B2BEB5;"><h2 class="text-lg font-bold text-black">Employment and Remarks</h2><div class="grid grid-cols-1 md:grid-cols-2 gap-4">@foreach (['employment_generated_male' => 'Employment Generated — Male', 'employment_generated_female' => 'Employment Generated — Female'] as $field => $label)<div><label class="block text-sm font-medium text-black">{{ $label }}</label><input type="number" min="0" name="{{ $field }}" value="{{ old($field, $data[$field] ?? '') }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;"></div>@endforeach</div><div><label class="block text-sm font-medium text-black">Remarks</label><textarea name="remarks" rows="3" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" style="border-color: #B2BEB5; color: black;">{{ old('remarks', $data['remarks'] ?? '') }}</textarea></div></div>
        @include('department.projects.forms.signatories', ['project' => $project, 'data' => $data])
        <div class="flex justify-end space-x-3"><a href="{{ route('department.projects.show', $project->project_id) }}" class="px-4 py-2 rounded" style="background-color: #e5e7eb;">Cancel</a>@if ($form)<a href="{{ route('department.projects.forms.pdf', [$project->project_id, 'form_2']) }}" class="px-4 py-2 rounded" style="background-color: #c9a84c; color: #0f1e3d;">Download PDF</a>@else<span title="Save the form first before generating a PDF" class="px-4 py-2 rounded cursor-not-allowed" style="background-color: #e5e7eb; color: #9ca3af;">Download PDF</span>@endif<button type="submit" class="px-4 py-2 rounded" style="background-color: #162347; color: #f2f3f7;">Save Form</button></div>
    </form>
</div>
@endsection
