@extends('layouts.admin')

@section('content')
<div class="space-y-6">
    <div>
        <h1 class="text-3xl font-bold" style="color: #1F2937;">Reports</h1>
        <p style="color: #6B7280;">View and export system reports when records are available.</p>
    </div>

    <div class="bg-white rounded-lg p-6" style="border: 1px solid #E5E7EB;">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <th class="text-left py-3 px-4 font-semibold text-gray-500 text-xs uppercase">Report Name</th>
                        <th class="text-left py-3 px-4 font-semibold text-gray-500 text-xs uppercase">Report Type</th>
                        <th class="text-left py-3 px-4 font-semibold text-gray-500 text-xs uppercase">Generated By</th>
                        <th class="text-left py-3 px-4 font-semibold text-gray-500 text-xs uppercase">Date Generated</th>
                        <th class="text-left py-3 px-4 font-semibold text-gray-500 text-xs uppercase">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5" class="py-6 px-4 text-sm text-gray-500">No reports have been generated yet.</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
