@extends('layouts.admin')

@section('content')
<div class="space-y-6">
    <div>
        <h1 class="text-3xl font-bold" style="color: #1F2937;">Reports</h1>
        <p style="color: #6B7280;">View and export system usage reports, user activity logs, and data quality metrics.</p>
    </div>

    <div class="flex justify-between items-center">
        <div class="flex items-center gap-4 flex-1">
            <div class="relative flex-1 max-w-md">
                <svg class="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5" style="color: #9CA3AF;" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
                <input type="text" placeholder="Search reports..." class="w-full pl-10 pr-4 py-2 rounded border" style="border-color: #D1D5DB; background-color: #ffffff; color: #1F2937;">
            </div>
            <button class="px-4 py-2 rounded flex items-center gap-2" style="background-color: #ffffff; border: 1px solid #D1D5DB; color: #1F2937;">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"></path>
                </svg>
                Filter
            </button>
        </div>
        <button class="px-4 py-2 rounded flex items-center gap-2" style="background-color: #1F2937; color: white;">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
            </svg>
            Export All
        </button>
    </div>

    <div class="bg-white rounded-lg p-6" style="background-color: #ffffff; border: 1px solid #E5E7EB;">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">REPORT NAME</th>
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">REPORT TYPE</th>
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">GENERATED BY</th>
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">DATE GENERATED</th>
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">STATUS</th>
                        <th class="text-left py-3 px-4 font-semibold" style="color: #6B7280; font-size: 0.75rem; letter-spacing: 0.05em;">ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <td class="py-3 px-4" style="color: #1F2937; font-weight: 500;">Monthly User Activity Report</td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">User Activity</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Ricardo Mabini</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Nov 24, 2023</span></td>
                        <td class="py-3 px-4"><span class="px-2 py-1 rounded text-xs font-semibold" style="background-color: #DCFCE7; color: #15803D;">COMPLETED</span></td>
                        <td class="py-3 px-4">
                            <button class="text-sm" style="color: #2563EB;">View</button>
                        </td>
                    </tr>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <td class="py-3 px-4" style="color: #1F2937; font-weight: 500;">SOLO Compliance Report Q4 0003</td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Compliance</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Maria Clara Santos</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Nov 22, 2023</span></td>
                        <td class="py-3 px-4"><span class="px-2 py-1 rounded text-xs font-semibold" style="background-color: #FED7AA; color: #B45309;">PENDING</span></td>
                        <td class="py-3 px-4">
                            <button class="text-sm" style="color: #2563EB;">View</button>
                        </td>
                    </tr>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <td class="py-3 px-4" style="color: #1F2937; font-weight: 500;">System Uptime & Latency Metrics</td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">System Usage</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Antonio Luna</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Nov 21, 2023</span></td>
                        <td class="py-3 px-4"><span class="px-2 py-1 rounded text-xs font-semibold" style="background-color: #DCFCE7; color: #15803D;">COMPLETED</span></td>
                        <td class="py-3 px-4">
                            <button class="text-sm" style="color: #2563EB;">View</button>
                        </td>
                    </tr>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <td class="py-3 px-4" style="color: #1F2937; font-weight: 500;">Data Integrity Audit - Barangay Records</td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Data Quality</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Teresa Magbanua</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Nov 20, 2023</span></td>
                        <td class="py-3 px-4"><span class="px-2 py-1 rounded text-xs font-semibold" style="background-color: #DCFCE7; color: #15803D;">COMPLETED</span></td>
                        <td class="py-3 px-4">
                            <button class="text-sm" style="color: #2563EB;">View</button>
                        </td>
                    </tr>
                    <tr style="border-bottom: 1px solid #E5E7EB;">
                        <td class="py-3 px-4" style="color: #1F2937; font-weight: 500;">Staff Login/Logout Terminal Log</td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">User Activity</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Emilio Aguinaldo</span></td>
                        <td class="py-3 px-4"><span style="color: #6B7280;">Nov 19, 2023</span></td>
                        <td class="py-3 px-4"><span class="px-2 py-1 rounded text-xs font-semibold" style="background-color: #DCFCE7; color: #15803D;">COMPLETED</span></td>
                        <td class="py-3 px-4">
                            <button class="text-sm" style="color: #2563EB;">View</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="flex items-center justify-between mt-6 pt-4" style="border-top: 1px solid #E5E7EB;">
            <p class="text-sm" style="color: #6B7280;">Showing 5 of 128 Reports</p>
            <div class="flex gap-2">
                <button class="px-3 py-1 rounded text-sm" style="background-color: #ffffff; color: #6B7280; border: 1px solid #D1D5DB;">← Prev</button>
                <button class="px-3 py-1 rounded text-sm font-semibold" style="background-color: #2563EB; color: white;">1</button>
                <button class="px-3 py-1 rounded text-sm" style="background-color: #ffffff; color: #6B7280; border: 1px solid #D1D5DB;">2</button>
                <button class="px-3 py-1 rounded text-sm" style="background-color: #ffffff; color: #6B7280; border: 1px solid #D1D5DB;">3</button>
                <button class="px-3 py-1 rounded text-sm" style="background-color: #ffffff; color: #6B7280; border: 1px solid #D1D5DB;">...</button>
                <button class="px-3 py-1 rounded text-sm" style="background-color: #ffffff; color: #6B7280; border: 1px solid #D1D5DB;">Next →</button>
            </div>
        </div>
    </div>
</div>
@endsection
