<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #0F1E3D; padding-bottom: 10px; }
        .header h1 { color: #0F1E3D; font-size: 18px; margin-bottom: 5px; }
        .header p { color: #666; font-size: 10px; }
        .metadata { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 10px; color: #666; }
        .section-title { background: #0F1E3D; color: white; padding: 8px; margin-top: 20px; margin-bottom: 10px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th { background: #c9a84c; color: #0F1E3D; padding: 8px; text-align: left; font-weight: bold; font-size: 10px; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9f9f9; }
        .text-right { text-align: right; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>City Transparency Portal</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
    </div>

    <div class="section-title">Actions Recorded</div>
    <table>
        <thead>
            <tr>
                <th>Action</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($audit_stats as $stat)
                <tr>
                    <td>{{ ucfirst($stat->action) }}</td>
                    <td class="text-right">{{ $stat->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Top Users by Activity</div>
    <table>
        <thead>
            <tr>
                <th>User</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($top_users as $entry)
                <tr>
                    <td>{{ $entry->user?->username ?? 'Unknown' }}</td>
                    <td class="text-right">{{ $entry->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Peak Usage Hours</div>
    <table>
        <thead>
            <tr>
                <th>Hour</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($peak_usage as $entry)
                <tr>
                    <td>{{ sprintf('%02d:00 - %02d:00', (int) $entry->hour, ((int) $entry->hour + 1) % 24) }}</td>
                    <td class="text-right">{{ $entry->total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Confidential — For Internal Use Only</p>
    </div>
</body>
</html>
