<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #0F1E3D; padding-bottom: 10px; }
        .header h1 { color: #0F1E3D; font-size: 18px; margin-bottom: 5px; }
        .header p { color: #666; font-size: 10px; }
        .metadata { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 10px; color: #666; }
        .table-wrap { width: 100%; border-collapse: collapse; }
        .table-wrap th, .table-wrap td { border: 1px solid #ddd; padding: 8px; }
        .table-wrap th { background: #c9a84c; color: #0F1E3D; font-weight: bold; text-align: left; font-size: 10px; }
        .table-wrap tbody tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; }
        .details { font-size: 9px; color: #444; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>City Transparency Portal</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
    </div>

    <table class="table-wrap">
        <thead>
            <tr>
                <th>Date</th>
                <th>User</th>
                <th>Full Name</th>
                <th>Action</th>
                <th>Table</th>
                <th>Record ID</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($logs as $log)
                <tr>
                    <td>{{ $log->created_at?->format('M d, Y h:i A') }}</td>
                    <td>{{ $log->user->username ?? 'Unknown' }}</td>
                    <td>{{ $log->full_name ?: ($log->user->full_name ?? 'Unknown') }}</td>
                    <td>{{ ucfirst($log->action) }}</td>
                    <td>{{ $log->table_name }}</td>
                    <td>{{ $log->record_id }}</td>
                    <td class="details">
                        @php
                            $keyFields = [
                                'project_name',
                                'current_status',
                                'approved_budget',
                                'actual_budget',
                                'start_date',
                                'target_end_date',
                                'actual_end_date',
                                'barangay_id',
                            ];
                            $dateFields = ['start_date', 'target_end_date', 'actual_end_date'];
                        @endphp

                        @if(!empty($log->old_values))
                            @php $oldFiltered = array_intersect_key((array) $log->old_values, array_flip($keyFields)); @endphp
                            @if(!empty($oldFiltered))
                                <div style="font-size:9px;"><strong>Old:</strong>
                                @foreach($oldFiltered as $key => $value)
                                    @php
                                        $display = is_array($value) ? json_encode($value) : $value;
                                        if (in_array($key, $dateFields, true) && !empty($display)) {
                                            $ts = strtotime($display);
                                            if ($ts !== false) {
                                                $display = date('M d, Y', $ts);
                                            }
                                        }
                                    @endphp
                                    {{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $display }}@if(!$loop->last), @endif
                                @endforeach
                                </div>
                            @endif
                        @endif

                        @if(!empty($log->new_values))
                            @php $newFiltered = array_intersect_key((array) $log->new_values, array_flip($keyFields)); @endphp
                            @if(!empty($newFiltered))
                                <div style="font-size:9px;"><strong>New:</strong>
                                @foreach($newFiltered as $key => $value)
                                    @php
                                        $display = is_array($value) ? json_encode($value) : $value;
                                        if (in_array($key, $dateFields, true) && !empty($display)) {
                                            $ts = strtotime($display);
                                            if ($ts !== false) {
                                                $display = date('M d, Y', $ts);
                                            }
                                        }
                                    @endphp
                                    {{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $display }}@if(!$loop->last), @endif
                                @endforeach
                                </div>
                            @endif
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by the City Transparency Portal.</p>
    </div>
</body>
</html>
