<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Budget Analysis Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; color: #1f2937; font-size: 11px; line-height: 1.5; background: #fff; }
        .page { padding: 28px 32px; }
        .header { display: flex; flex-direction: column; gap: 6px; margin-bottom: 24px; }
        .brand { font-size: 22px; font-weight: 700; color: #0f172a; letter-spacing: -0.02em; }
        .subtitle { font-size: 12px; color: #475569; }
        .metadata { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 8px; font-size: 10px; color: #475569; }
        .metadata span { display: inline-flex; gap: 4px; align-items: center; }
        .summary-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; margin-bottom: 22px; }
        .summary-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 16px; padding: 14px 16px; }
        .summary-card h2 { margin-bottom: 8px; font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase; color: #6b7280; }
        .summary-card p { margin: 0; font-size: 20px; font-weight: 700; color: #0f172a; }
        .summary-card .note { margin-top: 8px; font-size: 9px; color: #475569; line-height: 1.4; }
        .section-title { margin-top: 20px; margin-bottom: 10px; font-size: 11px; font-weight: 700; color: #0f172a; letter-spacing: 0.08em; text-transform: uppercase; }
        .table-wrapper { border: 1px solid #e2e8f0; border-radius: 14px; overflow: hidden; }
        table { width: 100%; border-collapse: collapse; }
        thead { background: #0f172a; color: #f8fafc; }
        th, td { padding: 11px 12px; }
        th { font-size: 10px; font-weight: 700; text-align: left; letter-spacing: 0.04em; }
        td { font-size: 10px; color: #334155; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        tbody tr:nth-child(even) { background: #f8fafc; }
        .text-right { text-align: right; }
        .footer { margin-top: 24px; padding-top: 14px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #6b7280; }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <div class="brand">Budget Analysis Report</div>
            <div class="subtitle">City Transparency Portal</div>
            <div class="metadata">
                <span><strong>Generated by:</strong> {{ $generated_by }}</span>
                <span><strong>Date:</strong> {{ $generated_date }}</span>
                <span><strong>Total Budget:</strong> &#8369;{{ number_format($total_budget, 2) }}</span>
            </div>
        </div>

        <div class="summary-grid">
            <div class="summary-card">
                <h2>Total Budget Allocated</h2>
                <p>&#8369;{{ number_format($total_budget, 2) }}</p>
                <div class="note">Approved allocation across all projects.</div>
            </div>
            <div class="summary-card">
                <h2>Total Budget Spent</h2>
                <p>&#8369;{{ number_format($total_spent, 2) }}</p>
                <div class="note">Recorded expenditures for all projects.</div>
            </div>
            <div class="summary-card">
                <h2>Remaining Balance</h2>
                <p>&#8369;{{ number_format($total_budget - $total_spent, 2) }}</p>
                <div class="note">Unspent budget available for projects.</div>
            </div>
        </div>

        <div class="section-title">Breakdown by Status</div>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Status</th>
                        <th class="text-right">Count</th>
                        <th class="text-right">Budget</th>
                        <th class="text-right">Spent</th>
                        <th class="text-right">Balance</th>
                    </tr>
        </thead>
        <tbody>
            @foreach ($by_status as $status => $stats)
                <tr>
                    <td>{{ $status }}</td>
                    <td class="text-right">{{ $stats['count'] }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['budget'], 2) }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['spent'], 2) }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['budget'] - $stats['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- By Barangay -->
    <div class="section-title">Breakdown by Barangay</div>
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Barangay</th>
                    <th class="text-right">Count</th>
                    <th class="text-right">Budget</th>
                    <th class="text-right">Spent</th>
                    <th class="text-right">Balance</th>
                </tr>
        <tbody>
            @foreach ($by_barangay as $barangay => $stats)
                <tr>
                    <td>{{ $barangay }}</td>
                    <td class="text-right">{{ $stats['count'] }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['budget'], 2) }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['spent'], 2) }}</td>
                    <td class="text-right">&#8369;{{ number_format($stats['budget'] - $stats['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
        </div>

        <div class="footer">
            <p>This is an official report generated by the City Transparency Portal. All data is considered public record.</p>
        </div>
    </div>
</body>
</html>