<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Budget Analysis Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #0F1E3D; padding-bottom: 10px; }
        .header h1 { color: #0F1E3D; font-size: 18px; margin-bottom: 5px; }
        .header p { color: #666; font-size: 10px; }
        .metadata { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 10px; color: #666; }
        .section-title { background: #0F1E3D; color: white; padding: 8px; margin-top: 20px; margin-bottom: 10px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th { background: #c9a84c; color: #0F1E3D; padding: 8px; text-align: left; font-weight: bold; font-size: 10px; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9f9f9; }
        .text-right { text-align: right; }
        .summary-box { background: #f5f5f5; border-left: 3px solid #0F1E3D; padding: 10px; margin: 10px 0; }
        .summary-row { display: flex; justify-content: space-between; padding: 5px 0; }
        .summary-label { font-weight: bold; }
        .summary-value { text-align: right; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Budget Analysis Report</h1>
        <p>City Transparency Portal</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
    </div>

    <!-- By Status -->
    <div class="section-title">Breakdown by Status</div>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th class="text-right">Count</th>
                <th class="text-right">Budget</th>
                <th class="text-right">Spent</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($by_status as $status => $stats)
                <tr>
                    <td>{{ $status }}</td>
                    <td class="text-right">{{ $stats['count'] }}</td>
                    <td class="text-right">₱{{ number_format($stats['budget'], 2) }}</td>
                    <td class="text-right">₱{{ number_format($stats['spent'], 2) }}</td>
                    <td class="text-right">₱{{ number_format($stats['budget'] - $stats['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- By Barangay -->
    <div class="section-title">Breakdown by Barangay</div>
    <table>
        <thead>
            <tr>
                <th>Barangay</th>
                <th class="text-right">Count</th>
                <th class="text-right">Budget</th>
                <th class="text-right">Spent</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($by_barangay as $barangay => $stats)
                <tr>
                    <td>{{ $barangay }}</td>
                    <td class="text-right">{{ $stats['count'] }}</td>
                    <td class="text-right">₱{{ number_format($stats['budget'], 2) }}</td>
                    <td class="text-right">₱{{ number_format($stats['spent'], 2) }}</td>
                    <td class="text-right">₱{{ number_format($stats['budget'] - $stats['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Summary -->
    <div class="section-title">Summary</div>
    <div class="summary-box">
        <div class="summary-row">
            <span class="summary-label">Total Budget Allocated:</span>
            <span class="summary-value">₱{{ number_format($total_budget, 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Budget Spent:</span>
            <span class="summary-value">₱{{ number_format($total_spent, 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Remaining Balance:</span>
            <span class="summary-value">₱{{ number_format($total_budget - $total_spent, 2) }}</span>
        </div>
    </div>

    <div class="footer">
        <p>This is an official report generated by the City Transparency Portal. All data is considered public record.</p>
    </div>
</body>
</html>