<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; color: #172033; font-size: 11px; line-height: 1.4; background: #f4f6f8; }
        .header { text-align: left; margin-bottom: 20px; background: #0b1220; border-bottom: 4px solid #c9a84c; padding: 18px 20px 15px; }
        .header h1 { color: #ffffff; font-size: 18px; margin-bottom: 5px; }
        .header p { color: #d6deeb; font-size: 10px; }
        .metadata { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 10px; color: #666; }
        .section-title { background: #162347; color: white; padding: 8px 10px; margin-top: 20px; margin-bottom: 10px; font-weight: bold; border-left: 4px solid #c9a84c; }
        .summary-box { background: #172b4d; color: #ffffff; border-left: 4px solid #c9a84c; padding: 10px; margin: 10px 0; }
        .summary-row { display: flex; justify-content: space-between; padding: 5px 0; }
        .summary-label { font-weight: bold; }
        .summary-value { text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th { background: #c9a84c; color: #0b1220; padding: 8px; text-align: left; font-weight: bold; font-size: 10px; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #eef2f7; }
        .text-right { text-align: right; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>City Transparency Portal</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
    </div>

    <div class="summary-box">
        <div class="summary-row">
            <span class="summary-label">Incomplete Project Records</span>
            <span class="summary-value">{{ $data_quality['incomplete_projects'] }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Missing Coordinates</span>
            <span class="summary-value">{{ $data_quality['missing_coordinates'] }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Missing Budget Data</span>
            <span class="summary-value">{{ $data_quality['missing_budget'] }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Orphaned/Potential Orphaned Records</span>
            <span class="summary-value">{{ $data_quality['orphaned_projects'] }}</span>
        </div>
    </div>

    <div class="footer">
        <p>Confidential � For Internal Use Only</p>
    </div>
</body>
</html>
