<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1a1a1a; }
.header { text-align: center; margin-bottom: 18px; border-bottom: 2px solid #0f1e3d; padding-bottom: 10px; } .header h1 { font-size: 18px; margin: 0; color: #0f1e3d; } .header p { font-size: 11px; color: #555; margin: 4px 0 0; }
.meta { font-size: 10px; color: #666; margin-bottom: 16px; } h2 { font-size: 13px; color: #0f1e3d; margin: 18px 0 8px; }
table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #B2BEB5; padding: 7px 8px; text-align: left; vertical-align: top; } th { background: #f2f3f7; font-weight: bold; } .label { width: 34%; font-weight: bold; color: #0f1e3d; } .empty { color: #666; font-style: italic; }
.signatories { margin-top: 25px; } .signatories td { width: 50%; height: 72px; } .signatories strong { color: #0f1e3d; } .footer { margin-top: 25px; font-size: 9px; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 8px; }
</style></head><body>
<div class="header"><h1>{{ $form_title }}</h1><p>Form {{ $form_number }} &mdash; {{ $project->project_name }} ({{ $project->project_code }})</p></div>
<div class="meta">Generated on: {{ now()->format('M d, Y h:i A') }}</div>
@php($formData = $form->form_data ?? [])
@if (empty($formData))<p class="empty">Not yet filled out.</p>@else
<h2>Form Details</h2><table><tbody>
@foreach ($formData as $key => $value)
@continue(in_array($key, ['submitted_by', 'submitted_designation', 'submitted_date', 'approved_by', 'approved_designation', 'approved_date', 'monthly'], true))
<tr><td class="label">{{ $field_labels[$key] ?? ucwords(str_replace('_', ' ', $key)) }}</td><td>@if(is_array($value))<ul style="margin:0; padding-left:15px;">@foreach($value as $itemKey => $itemValue)<li>{{ is_array($itemValue) ? $itemKey . ': ' . implode(', ', $itemValue) : $itemValue }}</li>@endforeach</ul>@else{{ $value ?: '—' }}@endif</td></tr>
@endforeach
</tbody></table>
@if (!empty($formData['monthly']) && is_array($formData['monthly']))<h2>Monthly Targets</h2><table><thead><tr><th>Month</th><th>Financial Target</th><th>Physical Target</th><th>OI 1</th><th>OI 2</th><th>OI 3</th><th>OI 4</th><th>OI 5</th></tr></thead><tbody>@foreach($formData['monthly'] as $month => $targets)<tr><td>{{ ucfirst($month) }}</td><td>{{ $targets['financial_target'] ?? '—' }}</td><td>{{ $targets['physical_target'] ?? '—' }}</td><td>{{ $targets['oi_1'] ?? '—' }}</td><td>{{ $targets['oi_2'] ?? '—' }}</td><td>{{ $targets['oi_3'] ?? '—' }}</td><td>{{ $targets['oi_4'] ?? '—' }}</td><td>{{ $targets['oi_5'] ?? '—' }}</td></tr>@endforeach</tbody></table>@endif
@endif
<table class="signatories"><tr><td><strong>Submitted By</strong><br><br>{{ $formData['submitted_by'] ?? '—' }}<br>{{ $formData['submitted_designation'] ?? '—' }}<br>{{ $formData['submitted_date'] ?? '—' }}</td><td><strong>Approved By</strong><br><br>{{ $formData['approved_by'] ?? '—' }}<br>{{ $formData['approved_designation'] ?? '—' }}<br>{{ $formData['approved_date'] ?? '—' }}</td></tr></table>
<div class="footer">Generated by the Department Project Forms System &middot; For Official Use Only</div></body></html>
