<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; color: #333; font-size: 11px; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #0F1E3D; padding-bottom: 10px; }
        .header h1 { color: #0F1E3D; font-size: 18px; margin-bottom: 5px; }
        .header p { color: #666; font-size: 10px; }
        .metadata { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 10px; color: #666; }
        .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 20px; }
        .stat-box { background: #f5f5f5; padding: 10px; border-left: 3px solid #c9a84c; }
        .stat-label { font-size: 9px; color: #999; text-transform: uppercase; margin-bottom: 3px; }
        .stat-value { font-size: 16px; font-weight: bold; color: #0F1E3D; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th { background: #0F1E3D; color: white; padding: 8px; text-align: left; font-weight: bold; font-size: 10px; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        tr:nth-child(even) { background: #f9f9f9; }
        .text-right { text-align: right; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>City Transparency Portal</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
    </div>

    <div class="stats">
        <div class="stat-box">
            <div class="stat-label">Total Projects</div>
            <div class="stat-value">{{ $total_projects }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Ongoing</div>
            <div class="stat-value">{{ $ongoing }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Completed</div>
            <div class="stat-value">{{ $completed }}</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Total Budget</div>
            <div class="stat-value">₱{{ number_format($total_budget, 0) }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Type</th>
                <th>Barangay</th>
                <th>Status</th>
                <th>Start Date</th>
                <th>Target End</th>
                <th class="text-right">Budget</th>
                <th class="text-right">Spent</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($projects as $project)
                <tr>
                    <td>{{ $project['code'] }}</td>
                    <td>{{ $project['name'] }}</td>
                    <td>{{ $project['type'] }}</td>
                    <td>{{ $project['barangay'] }}</td>
                    <td>{{ $project['status'] }}</td>
                    <td>{{ $project['start_date'] }}</td>
                    <td>{{ $project['end_date'] }}</td>
                    <td class="text-right">₱{{ number_format($project['budget'], 2) }}</td>
                    <td class="text-right">₱{{ number_format($project['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official report generated by the City Transparency Portal. All data is considered public record.</p>
    </div>
</body>
</html>