<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #25304b; font-size: 11px; line-height: 1.5; background: #fff; }
        .page { padding: 24px 28px; }
        .header { text-align: left; margin-bottom: 22px; border-bottom: 3px solid #0F1E3D; padding-bottom: 14px; }
        .header h1 { color: #0F1E3D; font-size: 22px; margin-bottom: 6px; letter-spacing: -0.02em; }
        .header p { color: #6b7280; font-size: 11px; }
        .metadata { display: flex; justify-content: space-between; flex-wrap: wrap; gap: 10px; margin-bottom: 20px; font-size: 10px; color: #4b5563; }
        .metadata span { display: inline-flex; gap: 4px; align-items: center; }
        .metadata strong { color: #111827; }
        .stats { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 10px; margin-bottom: 24px; }
        .stat-box { background: #f8fafc; padding: 12px 14px; border-radius: 10px; border: 1px solid #e2e8f0; }
        .stat-label { font-size: 8.5px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 4px; }
        .stat-value { font-size: 16px; font-weight: 700; color: #111827; }
        .stat-secondary { font-size: 9px; color: #475569; margin-top: 3px; }
        .table-wrapper { border: 1px solid #e2e8f0; border-radius: 14px; overflow: hidden; }
        table { width: 100%; border-collapse: collapse; }
        thead { background: #0f172a; }
        th { color: #ffffff; padding: 10px 12px; text-align: left; font-weight: 700; font-size: 9px; text-transform: uppercase; letter-spacing: 0.05em; }
        td { padding: 11px 12px; border-bottom: 1px solid #e2e8f0; vertical-align: top; font-size: 10px; color: #334155; }
        tbody tr:nth-child(even) { background: #f8fafc; }
        .text-right { text-align: right; }
        .summary-row td { border-top: 2px solid #cbd5e1; font-weight: 700; background: #f1f5f9; }
        .footer { margin-top: 22px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #64748b; }
        .small { font-size: 9px; color: #64748b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Official Cabuyao Project Tracker report</p>
    </div>

    <div class="metadata">
        <span><strong>Generated by:</strong> {{ $generated_by }}</span>
        <span><strong>Date:</strong> {{ $generated_date }}</span>
        <span class="small"><strong>Record count:</strong> {{ $total_projects }} projects</span>
    </div>

    <div class="stats">
        <div class="stat-box">
            <div class="stat-label">Total Projects</div>
            <div class="stat-value">{{ $total_projects }}</div>
            <div class="stat-secondary">All active projects</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Ongoing</div>
            <div class="stat-value">{{ $ongoing }}</div>
            <div class="stat-secondary">Currently in progress</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Completed</div>
            <div class="stat-value">{{ $completed }}</div>
            <div class="stat-secondary">Closed projects</div>
        </div>
        <div class="stat-box">
            <div class="stat-label">Total Budget</div>
            <div class="stat-value">&#8369;{{ number_format($total_budget, 0) }}</div>
            <div class="stat-secondary">Approved budget</div>
        </div>
    </div>

    <div class="table-wrapper">
        <table>
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Type</th>
                <th>Barangay</th>
                <th>Status</th>
                <th>Start Date</th>
                <th>Target End</th>
                <th class="text-right">Budget</th>
                <th class="text-right">Spent</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($projects as $project)
                <tr>
                    <td>{{ $project['code'] }}</td>
                    <td>{{ $project['name'] }}</td>
                    <td>{{ $project['type'] }}</td>
                    <td>{{ $project['barangay'] }}</td>
                    <td>{{ $project['status'] }}</td>
                    <td>{{ $project['start_date'] }}</td>
                    <td>{{ $project['end_date'] }}</td>
                    <td class="text-right">&#8369;{{ number_format($project['budget'], 2) }}</td>
                    <td class="text-right">&#8369;{{ number_format($project['spent'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    </div>

    <div class="footer">
        <p>This is an official report generated by the City Transparency Portal. All data is considered public record.</p>
    </div>
</body>
</html>