<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #0f1e3d; padding-bottom: 10px; }
        .header h1 { font-size: 18px; margin: 0; color: #0f1e3d; }
        .header p { font-size: 11px; color: #555; margin: 4px 0 0; }
        .meta { font-size: 10px; color: #666; margin-bottom: 20px; }
        .summary-grid { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .summary-grid td { border: 1px solid #B2BEB5; padding: 8px 10px; width: 50%; }
        .summary-label { font-size: 10px; color: #555; }
        .summary-value { font-size: 16px; font-weight: bold; color: #0f1e3d; }
        table.data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.data-table th, table.data-table td { border: 1px solid #B2BEB5; padding: 6px 8px; text-align: left; font-size: 10px; }
        table.data-table th { background-color: #f2f3f7; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 9px; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 8px; }
        h2 { font-size: 13px; color: #0f1e3d; margin-top: 20px; margin-bottom: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>SGLG Compliance Report — Cabuyao City</h1>
        <p>Seal of Good Local Governance — Project Monitoring &amp; Transparency Documentation</p>
    </div>

    <div class="meta">
        Generated by: {{ $generated_by }} &middot; Generated on: {{ $generated_date }}
    </div>

    <h2>Summary Indicators</h2>
    <table class="summary-grid">
        <tr>
            <td>
                <div class="summary-label">Documentation Rate</div>
                <div class="summary-value">{{ $summary['documentation_rate'] }}%</div>
                <div class="summary-label">{{ $summary['projects_with_documentation'] }} of {{ $summary['total_projects'] }} projects</div>
            </td>
            <td>
                <div class="summary-label">Up-to-Date Rate (updated within 90 days)</div>
                <div class="summary-value">{{ $summary['up_to_date_rate'] }}%</div>
                <div class="summary-label">{{ $summary['projects_recently_updated'] }} of {{ $summary['total_projects'] }} projects</div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="summary-label">Transparency Rate (visible on public portal)</div>
                <div class="summary-value">{{ $summary['transparency_rate'] }}%</div>
                <div class="summary-label">{{ $summary['projects_published'] }} of {{ $summary['total_projects'] }} projects</div>
            </td>
            <td>
                <div class="summary-label">Budget Utilization Rate</div>
                <div class="summary-value">{{ $summary['budget_utilization_rate'] }}%</div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="summary-label">Completion Rate</div>
                <div class="summary-value">{{ $summary['completion_rate'] }}%</div>
            </td>
            <td>
                <div class="summary-label">Total Projects in Scope</div>
                <div class="summary-value">{{ $summary['total_projects'] }}</div>
            </td>
        </tr>
    </table>

    <h2>Breakdown by Barangay</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Barangay</th>
                <th>Project Count</th>
                <th>Documentation Rate</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($by_barangay as $barangayName => $stats)
                <tr>
                    <td>{{ $barangayName }}</td>
                    <td>{{ $stats['count'] }}</td>
                    <td>{{ $stats['documentation_rate'] }}%</td>
                </tr>
            @empty
                <tr><td colspan="3">No data available.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Prepared for DILG Seal of Good Local Governance (SGLG) assessment purposes.<br>
        Confidential — For Official Use Only
    </div>
</body>
</html>